services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backups:/backups:ro
    env_file: 
      - ./db.env
    ports:
      - "5432:5432"
    networks:
      - djangonetwork

  django:
    env_file: 
      - ./db.env
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
     - "8000:8000"
    depends_on:
      - db
      - llm
    networks:
      - djangonetwork
    environment:
      - LLM_SERVICE_URL=http://llm:8001
  

  llm:
      build:
        context: ./fill_Llm
        dockerfile: Dockerfile
      
      
      command: "uvicorn main:llm --host 0.0.0.0 --port 8001"
      ports:
        - "8001:8001"
      networks:
        - djangonetwork




networks:
  djangonetwork:

volumes:
  pgdata: