# Generated by Django 5.2.3 on 2025-07-08 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Подробное описание категории')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская категория (если это подкатегория)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='budgetwise.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата транзакции')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Общая сумма чека (вводит пользователь)', max_digits=12)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Доход'), (1, 'Расход')], help_text='0 = Доход, 1 = Расход')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи')),
                ('category', models.ForeignKey(help_text='Категория транзакции', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgetwise.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование позиции', max_length=100)),
                ('product_type', models.CharField(help_text='Тип продукта', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за 1 шт.', max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, help_text='Сумма', max_digits=12)),
                ('category', models.ForeignKey(help_text='Категория позиции', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='budgetwise.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='budgetwise.transaction')),
            ],
        ),
    ]
