# Generated by Django 4.2.3 on 2025-06-30 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetwise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Положительное число для дохода, отрицательное — для расхода', max_digits=10)),
                ('date', models.DateField(help_text='Дата транзакции')),
                ('category', models.CharField(help_text='Категория транзакции', max_length=50)),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], help_text='Доход или расход', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
