# Generated by Django 4.2.3 on 2025-07-02 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование позиции', max_length=100)),
                ('product_type', models.CharField(help_text='Тип продукта', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за единицу', max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, help_text='Сумма (quantity * price)', max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Доход'), ('outcome', 'Расход')], help_text='Доход или расход (outcome)', max_length=7),
        ),
        migrations.AddField(
            model_name='position',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='budgetwise.transaction'),
        ),
    ]
