# Generated by Django 4.2.3 on 2025-07-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0007_remove_old_and_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория позиции', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='budgetwise.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена за 1 шт.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='sum',
            field=models.DecimalField(decimal_places=2, help_text='Сумма', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Категория транзакции', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgetwise.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Доход'), ('outcome', 'Расход')], help_text='Доход или расход', max_length=7),
        ),
    ]
