# Generated by Django 4.2.3 on 2025-07-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0008_alter_category_options_position_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='category',
            field=models.ForeignKey(help_text='Категория позиции', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='budgetwise.category'),
        ),
    ]
