# Generated by Django 4.2.3 on 2025-07-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0011_add_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительская категория (если это подкатегория)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='budgetwise.category'),
        ),
    ]
