# Generated by Django 5.2.3 on 2025-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0015_rename_type_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Доход'), (1, 'Расход')], help_text='0 = Доход, 1 = Расход'),
        ),
    ]
