# Generated by Django 5.2.3 on 2025-07-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0016_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Общая сумма чека (вводит пользователь)', max_digits=12),
        ),
    ]
